# Generated by Django 4.2.1 on 2023-07-26 02:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainFullInfo',
            fields=[
                ('trainCode', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('trainName', models.CharField(default='', max_length=256)),
                ('trName', models.CharField(default='')),
                ('srcStation', models.JSONField(default='{}')),
                ('destStation', models.JSONField(default='{}')),
                ('distance', models.IntegerField(default=0)),
                ('duration', models.CharField(default='', max_length=10)),
                ('halts', models.IntegerField(default=0)),
                ('trainId', models.IntegerField(default=0)),
                ('depTimeFromSrc', models.CharField(default='', max_length=10)),
                ('arrTimeAtDest', models.CharField(default='', max_length=10)),
                ('avgSpeed', models.CharField(default='', max_length=10)),
                ('depDays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=4), default=[''], size=7)),
                ('trname_telgu', models.CharField(default='')),
                ('trname_hindi', models.CharField(default='')),
                ('trname_bengali', models.CharField(default='')),
                ('trname_tamil', models.CharField(default='')),
                ('trname_kannada', models.CharField(default='')),
                ('trname_malyalam', models.CharField(default='')),
                ('trname_marathi', models.CharField(default='')),
                ('trname_gujrati', models.CharField(default='')),
                ('coach', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=''), size=None)),
                ('reversal', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=''), blank=True, size=None)),
                ('trainType', models.CharField(default='')),
                ('inaugural', models.CharField(default='')),
                ('wiki', models.CharField(default='')),
                ('sound', models.CharField(default='')),
                ('rake', models.CharField(default='')),
                ('trainRunsOn', models.CharField(default='')),
                ('haltsList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=''), blank=True, size=None)),
                ('arrDayTimeList', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=2), blank=True, default=[''], size=None)),
                ('depDayTimeList', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=2), blank=True, default=[''], size=None)),
                ('haltsDistList', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), blank=True, default=[0], size=None)),
                ('platformList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=0, max_length=20), blank=True, default=[''], size=None)),
            ],
        ),
    ]
