# Generated by Django 4.2.1 on 2023-07-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_trainfullinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainFullInfo',
        ),
    ]
