# Generated by Django 4.2.1 on 2023-08-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_stationsnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationsnew',
            name='near',
        ),
    ]
