# Generated by Django 4.2.1 on 2023-08-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_remove_stationsnew_near'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsnew',
            name='near',
            field=models.CharField(default=''),
        ),
    ]
