# Generated by Django 4.2.1 on 2023-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_remove_stationsnew_stname_tn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsnew',
            name='stname_hi',
            field=models.CharField(default=''),
        ),
    ]
