# Generated by Django 4.2.1 on 2023-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_stationsnew_stname_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationsnew',
            name='id',
        ),
        migrations.AlterField(
            model_name='stationsnew',
            name='stationCode',
            field=models.CharField(default='', primary_key=True, serialize=False),
        ),
    ]
