# Generated by Django 4.2.1 on 2023-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_alter_traininfo_arrtimeatdest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('trainName', models.CharField(default='')),
                ('trainNameOtherLang', models.JSONField()),
                ('trainCode', models.CharField(default='', primary_key=True, serialize=False)),
                ('srcStn', models.JSONField()),
                ('destStn', models.JSONField()),
                ('duration', models.CharField(default='')),
                ('runsOn', models.CharField(default='')),
                ('route', models.JSONField()),
                ('halts', models.IntegerField()),
            ],
        ),
    ]
